POST http://127.0.0.1:9000/api/recipes/
Content-Type: application/json
Authorization: Token a1c59cd98b91528c843623be7cb9b1f737bc3ed5

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 10
    },
    {
      "id": 113,
      "amount": 1
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1750
}