# docker-compose.production.yml
version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  foodgram_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
      
  backend:
    image: igornadein/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/app/media/
    depends_on:
      - foodgram_db

  frontend:
    image: igornadein/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/
  nginx:
    image: igornadein/foodgram_proxy
    volumes:
      - static_volume:/static/
      - media_volume:/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 7000:80
    depends_on:
      - backend
      - frontend

