PUT http://localhost:9000/api/users/me/avatar/
Content-Type: application/json
Authorization: Token a1c59cd98b91528c843623be7cb9b1f737bc3ed5

{
"avatar": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg=="
}