# Generated by Django 4.2.21 on 2025-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_shoppingcart_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='food.IngredientRecipe', to='food.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
