POST http://127.0.0.1:9000/api/recipes/101/shopping_cart/
Content-Type: application/json
Authorization: Token 160d6312a0fd2c93445a368892bf14b4eea9534e

{
"id": 101,
"name": "string",
"image": "/media/recipes/images/temp_tFqGPi6.png",
"cooking_time": 1750
}

