

GET  http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Content-Type: application/json
Authorization: Token 160d6312a0fd2c93445a368892bf14b4eea9534e
# Authorization: Token 26d0651b877990c26684cc4772642d1155e917d1

# {
# "id": 0,
# "name": "string",
# "image": "http://foodgram.example.org/media/recipes/images/image.png",
# "cooking_time": 1
# }