# Generated by Django 3.2.3 on 2025-05-18 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='users.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
